### ISSUE TITLE
我的手机是联想A3900，系统是android4.4.3   no root    4926-4926/com.ont.odvp.sample E/CrashReport: java.lang.NullPointerException  at com.ont.media.odvp.codec.AudioEncode.start(AudioEncode.java:95)

### ISSUE THREAD

**Issue by sgnah** [cm-heclouds/AndroidODVPSDK#1]
01-01 15:01:27.670 4926-5019/com.ont.odvp.sample I/OMXClient: Using client-side OMX mux.
01-01 15:01:27.680 4926-5019/com.ont.odvp.sample E/ACodec: [OMX.MARVELL.AUDIO.AACENCODER] configureCodec returning error -1010
01-01 15:01:27.680 4926-5019/com.ont.odvp.sample E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err: java.lang.IllegalStateException
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:262)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.ont.media.odvp.codec.AudioEncode.init(AudioEncode.java:80)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.ont.media.odvp.codec.EncodeMgr.start(EncodeMgr.java:85)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.ont.odvp.sample.publish.PublishProxy.startPublish(PublishProxy.java:141)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.ont.odvp.sample.publish.PublishActivity.startPublish(PublishActivity.java:264)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.ont.odvp.sample.publish.PublishActivity$3$1.onCallback(PublishActivity.java:108)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.ont.odvp.sample.device.OntOdvpProxy$1.run(OntOdvpProxy.java:144)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at android.os.Looper.loop(Looper.java:136)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5011)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample W/System.err:     at dalvik.system.NativeStart.main(Native Method)
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample D/dalvikvm: Trying to load lib /data/app-lib/com.ont.odvp.sample-2/libyuv.so 0x41a0d668
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample D/dalvikvm: Shared lib '/data/app-lib/com.ont.odvp.sample-2/libyuv.so' already loaded in same CL 0x41a0d668
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample D/dalvikvm: Trying to load lib /data/app-lib/com.ont.odvp.sample-2/libont_odvp.so 0x41a0d668
01-01 15:01:27.680 4926-4926/com.ont.odvp.sample D/dalvikvm: Shared lib '/data/app-lib/com.ont.odvp.sample-2/libont_odvp.so' already loaded in same CL 0x41a0d668
01-01 15:01:27.680 4926-5023/com.ont.odvp.sample I/OMXClient: Using client-side OMX mux.
01-01 15:01:27.690 4926-5023/com.ont.odvp.sample E/ACodec: [OMX.MARVELL.VIDEO.HW.CODA7542ENCODER] storeMetaDataInBuffers (output) failed w/ err -2147483648
01-01 15:01:27.690 4926-5023/com.ont.odvp.sample I/ACodec: setupVideoEncoder succeeded
01-01 15:01:27.690 4926-4926/com.ont.odvp.sample D/AndroidRuntime: Shutting down VM
01-01 15:01:27.690 4926-4926/com.ont.odvp.sample W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41718ba8)
01-01 15:01:27.690 4926-4926/com.ont.odvp.sample E/CrashReport: Java Crash Happen cause by main(1)
01-01 15:01:27.730 4926-4926/com.ont.odvp.sample I/CrashReport: [LogUtil] Get user log from native.
01-01 15:01:27.730 4926-4926/com.ont.odvp.sample I/CrashReport-Native: Native log has not been initiated.
01-01 15:01:27.740 4926-4926/com.ont.odvp.sample I/CrashReport: user log size:0
01-01 15:01:27.740 4926-4926/com.ont.odvp.sample E/CrashReport: stack frame :15, has cause false
01-01 15:01:27.750 4926-4926/com.ont.odvp.sample E/CrashReport: #++++++++++Record By Bugly++++++++++#
01-01 15:01:27.750 4926-4926/com.ont.odvp.sample E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
01-01 15:01:27.750 4926-4926/com.ont.odvp.sample E/CrashReport: # PKG NAME: com.ont.odvp.sample
01-01 15:01:27.750 4926-4926/com.ont.odvp.sample E/CrashReport: # APP VER: 1.0.0
01-01 15:01:27.750 4926-4926/com.ont.odvp.sample E/CrashReport: # LAUNCH TIME: 2015-01-01 15:01:02
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # CRASH TYPE: JAVA_CRASH
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # CRASH TIME: 2015-01-01 15:01:27
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # CRASH PROCESS: com.ont.odvp.sample
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # CRASH THREAD: main
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # REPORT ID: a9ac078e-7625-477d-aac6-69313aea3489
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # CRASH DEVICE: Lenovo A3900 UNROOT
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # RUNTIME AVAIL RAM:434384896 ROM:6137212928 SD:6146428928
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # RUNTIME TOTAL RAM:996704256 ROM:6506655744 SD:6454226944
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: # CRASH STACK: 
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: java.lang.NullPointerException
        at com.ont.media.odvp.codec.AudioEncode.start(AudioEncode.java:95)
        at com.ont.media.odvp.codec.EncodeMgr.start(EncodeMgr.java:90)
        at com.ont.odvp.sample.publish.PublishProxy.startPublish(PublishProxy.java:141)
        at com.ont.odvp.sample.publish.PublishActivity.startPublish(PublishActivity.java:264)
        at com.ont.odvp.sample.publish.PublishActivity$3$1.onCallback(PublishActivity.java:108)
        at com.ont.odvp.sample.device.OntOdvpProxy$1.run(OntOdvpProxy.java:144)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5011)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
        at dalvik.system.NativeStart.main(Native Method)
01-01 15:01:27.760 4926-4926/com.ont.odvp.sample E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
01-01 15:01:27.791 4926-4926/com.ont.odvp.sample D/CrashReport: [Database] deleted t_lr data 1
01-01 15:01:27.801 4926-4926/com.ont.odvp.sample D/CrashReport: [Database] insert t_lr success.
01-01 15:01:27.801 4926-4926/com.ont.odvp.sample I/CrashReportInfo: [crash] a crash occur, handling...
01-01 15:01:27.821 4926-4926/com.ont.odvp.sample D/CrashReport: [Database] insert t_cr success.
01-01 15:01:27.821 4926-4926/com.ont.odvp.sample D/CrashReport: insert t_cr success!
01-01 15:01:27.821 4926-4926/com.ont.odvp.sample I/CrashReportInfo: [crash] save crash success
01-01 15:01:27.821 4926-4926/com.ont.odvp.sample I/CrashReport: try to upload right now
01-01 15:01:27.821 4926-4926/com.ont.odvp.sample D/CrashReport: attach pageTracingList
01-01 15:01:27.821 4926-4926/com.ont.odvp.sample D/CrashReport: java.lang.NullPointerException rid:a9ac078e-7625-477d-aac6-69313aea3489 sess:f997455f-4095-46de-87d4-180bbe1654d5 ls:24s isR:false isF:true isM:false isN:false mc:0 ,null ,isUp:false ,vm:32
01-01 15:01:27.841 4926-4926/com.ont.odvp.sample D/CrashReport: [UploadManager] Add upload task (pid=4926 | tid=4926)
01-01 15:01:27.841 4926-4926/com.ont.odvp.sample D/CrashReport: [UploadManager] Sucessfully got session ID, try to execute upload task now (pid=4926 | tid=4926)
01-01 15:01:27.841 4926-4926/com.ont.odvp.sample D/CrashReport: [UploadManager] Execute synchronized upload task (pid=4926 | tid=4926)
01-01 15:01:27.841 4926-5028/com.ont.odvp.sample D/CrashReport: [UploadManager] Local network consume: 42 KB
01-01 15:01:27.841 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Run upload task with cmd: 830
01-01 15:01:27.851 4926-5028/com.ont.odvp.sample D/CrashReport: [UploadManager] Integrate security to HTTP headers (pid=4926 | tid=5028)
01-01 15:01:27.851 4926-5028/com.ont.odvp.sample D/CrashReport: [Util] Zip 21662 bytes data with type Gzip
01-01 15:01:27.881 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 11
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 12
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 13
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 14
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 15
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 16
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 17
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 18
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 19
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 20
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 21
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 22
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 23
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 24
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 25
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 26
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 27
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 28
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 29
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 30
01-01 15:01:27.891 4926-4933/com.ont.odvp.sample I/dalvikvm: Total arena pages for JIT: 31
01-01 15:01:27.911 4926-5028/com.ont.odvp.sample D/CrashReport: [Database] deleted t_lr data 1
01-01 15:01:27.911 4926-5028/com.ont.odvp.sample D/CrashReport: [Database] insert t_lr success.
01-01 15:01:27.911 4926-5028/com.ont.odvp.sample D/CrashReport: [UploadManager] Uploading(ID:1004) time: 2015-01-01 15:01:27
01-01 15:01:27.911 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Send 3865 bytes
01-01 15:01:27.911 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Upload to http://android.bugly.qq.com/rqd/async?aid=390dd7b3-389e-4843-81c2-c5ea84ce0dc1 with cmd 830 (pid=4926 | tid=5028).
01-01 15:01:27.911 4926-5028/com.ont.odvp.sample D/CrashReport: request: http://android.bugly.qq.com/rqd/async?aid=390dd7b3-389e-4843-81c2-c5ea84ce0dc1, send: 3865 (pid=4926 | tid=5028)
01-01 15:01:27.971 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Bugly version from headers is: bugly/1.0
01-01 15:01:27.971 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Status from server is 0 (pid=4926 | tid=5028).
01-01 15:01:27.971 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Received 130 bytes
01-01 15:01:27.971 4926-5028/com.ont.odvp.sample D/CrashReport: [Util] Unzip 114 bytes data with type Gzip
01-01 15:01:27.971 4926-5028/com.ont.odvp.sample D/CrashReport: [Upload] Response cmd is: 0, length of sBuffer is: 0
01-01 15:01:27.971 4926-5028/com.ont.odvp.sample I/CrashReport: [Upload] Success: crash
01-01 15:01:27.981 4926-5028/com.ont.odvp.sample D/CrashReport: [UploadManager] Local network consume: 42 KB
01-01 15:01:27.991 4926-5028/com.ont.odvp.sample D/CrashReport: [Database] deleted t_lr data 1
01-01 15:01:28.001 4926-5028/com.ont.odvp.sample D/CrashReport: [Database] insert t_lr success.
01-01 15:01:28.001 4926-5028/com.ont.odvp.sample D/CrashReport: [UploadManager] Network total consume: 46 KB
01-01 15:01:28.001 4926-5028/com.ont.odvp.sample D/CrashReport: up finish update state true
01-01 15:01:28.001 4926-5028/com.ont.odvp.sample D/CrashReport: pre uid:a9ac078e-7625-477d-aac6-69313aea3489 uc:0 re:false me:false
01-01 15:01:28.001 4926-5028/com.ont.odvp.sample D/CrashReport: set uid:a9ac078e-7625-477d-aac6-69313aea3489 uc:1 re:true me:false
01-01 15:01:28.011 4926-5028/com.ont.odvp.sample D/CrashReport: [Database] insert t_cr success.
01-01 15:01:28.011 4926-5028/com.ont.odvp.sample D/CrashReport: insert t_cr success!
01-01 15:01:28.021 4926-5028/com.ont.odvp.sample D/CrashReport: update state size 1
01-01 15:01:28.021 4926-4926/com.ont.odvp.sample E/CrashReport: sys default last handle start!
01-01 15:01:28.021 4926-4926/com.ont.odvp.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ont.odvp.sample, PID: 4926
    java.lang.NullPointerException
        at com.ont.media.odvp.codec.AudioEncode.start(AudioEncode.java:95)
        at com.ont.media.odvp.codec.EncodeMgr.start(EncodeMgr.java:90)
        at com.ont.odvp.sample.publish.PublishProxy.startPublish(PublishProxy.java:141)
        at com.ont.odvp.sample.publish.PublishActivity.startPublish(PublishActivity.java:264)
        at com.ont.odvp.sample.publish.PublishActivity$3$1.onCallback(PublishActivity.java:108)
        at com.ont.odvp.sample.device.OntOdvpProxy$1.run(OntOdvpProxy.java:144)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5011)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
        at dalvik.system.NativeStart.main(Native Method)
01-01 15:01:28.031 616-883/? W/ActivityManager:   Force finishing activity com.ont.odvp.sample/.publish.PublishActivity
01-01 15:01:28.531 616-630/? W/ActivityManager: Activity pause timeout for ActivityRecord{4220d718 u0 com.ont.odvp.sample/.publish.PublishActivity t8 f}

**Comment by sgnah** [comment]
public boolean init() {

        MediaFormat audioFormat = MediaFormat.createAudioFormat(AUDIO_MIME_TYPE, mSampleRate, mChannelConfig == AudioFormat.CHANNEL_IN_STEREO ? 2 : 1);
        //audioFormat.setInteger(MediaFormat.KEY_AAC_PROFILE, MediaCodecInfo.CodecProfileLevel.AACObjectHE);
        audioFormat.setInteger(MediaFormat.KEY_BIT_RATE, mBitrate);
        audioFormat.setInteger(MediaFormat.KEY_MAX_INPUT_SIZE, AudioRecord.getMinBufferSize(mSampleRate, mChannelConfig, mFormat));

        try {
            mEncoder = MediaCodec.createEncoderByType(AUDIO_MIME_TYPE);
            mEncoder.configure(audioFormat, null /* surface */, null /* crypto */, MediaCodec.CONFIGURE_FLAG_ENCODE);
-----------------跟踪到这里就是异常，然后跳到下面的catch  中，mEncoder 就被置空 null; 然后调用 mEncoder.start就是出错了!
            mMp4Track = mMp4Record.addTrack(audioFormat);

        } catch (IOException | IllegalStateException e) {

            e.printStackTrace();
            mEncoder = null;
            return false;
        }
        return true;
    }

    public void start() {

        mBufferInfo = new MediaCodec.BufferInfo();
        mEncoder.start();
    }

**Comment by cm-heclouds** [comment]
崩溃1.0.1已修复
如果默认的编码参数手机不支持可以通过publishConfig重新设置
